services:
  backend:
    image: dineshkundo/react-java-mysql_backend:latest
    restart: always
    environment:
      MYSQL_HOST: db
    networks:
      - react-spring
      - spring-mysql
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: dineshkundo/react-java-mysql_frontend:latest
    ports:
      - 3000:3000
    networks:
      - react-spring
    depends_on:
      - backend

  db:
    image: mariadb:10.6.4-focal
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-mysql

secrets:
  db-password:
    file: /home/ubuntu/awesome-compose/react-java-mysql/db/password.txt

volumes:
  db-data: {}

networks:
  react-spring: {}
  spring-mysql: {}

